### ISSUE TITLE
Icon is generated in a wrong size

### ISSUE THREAD

**Issue by Stanzilla** [NotWoods/maskable#13]
My icon was generated as 117x117 instead of the requested 196x196. I used a 40% padding and kinda expected it to fill up.

**Comment by NotWoods** [comment]
Can you attach the files you used here?

**Comment by Stanzilla** [comment]
Yup, here you go 
![favicon-196](https://user-images.githubusercontent.com/75278/71561299-f993b000-2a74-11ea-8fef-bcb5d281c393.png)
