### ISSUE TITLE
Minimum Safe Image does not match chrome Dev Tools

### ISSUE THREAD

**Issue by sirugh** [NotWoods/maskable#31]
Cool tool :) It would be really nice if the output image matches the "show minimum safe image" in the chrome dev tools. Notice in the following images how chrome's y value is higher:

Maskable.app:
[![Image from Gyazo](https://i.gyazo.com/f81f2e43d34eeed9ff1ddbf9f6a1dcd1.png)](https://gyazo.com/f81f2e43d34eeed9ff1ddbf9f6a1dcd1)

Chrome Dev Tools:
[![Image from Gyazo](https://i.gyazo.com/c3de47d4e80b53b54f1725992d8df89e.png)](https://gyazo.com/c3de47d4e80b53b54f1725992d8df89e)

**Comment by NotWoods** [comment]
Do you mind attaching the image to the issue here? I'll test it out and try to fix the display

**Comment by sirugh** [comment]
Ah I don't know if I still have it but I'll try.

**Comment by atjn** [comment]
Maybe related: when testing my icon, I noticed that choosing the "flower" crop would sometimes cut off the corners of my logo, even though it was not cropped by "minimum safe area".

**Comment by NotWoods** [comment]
I'll double check the flower path, I may have incorrectly imported it from Nova Launcher.

I double checked the masking with the Maskable.app logo, and even updated it to be exactly 100x100 with a 80x80 circle. I can't see a difference between Chrome DevTools and Maskable.app.
![image](https://user-images.githubusercontent.com/1782266/161187275-cfcd253f-2527-485f-baca-ac38d51d8273.png)
