### ISSUE TITLE
Add export size 192x192

### ISSUE THREAD

**Issue by divall** [NotWoods/maskable#42]
I’ve checked the manifests of a bunch of popular PWAs, and the ones that implements maskable icons are mainly using two sizes, which are 192x192 and 512x512, so I suggest adding the export size 192x192 as well. There are also articles mentioning 196x196, but I have yet to find any PWA using that size.

**Comment by justingolden21** [comment]
I was just about to say, 48 and 192 should be here, at minimum.

What I would do is let users enter their own comma separated list, and then parse that.

For example, an input with the text "48,96,192,512" and the program reads it in, splits based off of commas and whitespace, removes empty items and removes non-numeric items, previews the numbers below, and then upon downloading, downloads each size (maybe limit 20 sizes)

They could also be stored as a url parameter, so someone could easily bookmark the page and reuse it, or share the page with others.

**Comment by justingolden21** [comment]
Awesome, just saw you added it with checkboxes : )

Hate to be that guy, but 72 and 96 are fairly common sizes at well, that would be very useful for PWAs, feel free to fact check me if you believe I'm wrong.

Also, I'd be willing to work on a PR to improve the UI for the checkboxes if you'd be ok with it : )

**Comment by NotWoods** [comment]
Thanks for the PR! Merged it in.

**Comment by justingolden21** [comment]
Awesome, thanks for the quick merge.

Confirmed it shows up and works in my browser rn after a hard refresh:

![image](https://user-images.githubusercontent.com/30274440/107293284-32e07280-6a20-11eb-917b-c26d125aaabc.png)
