### ISSUE TITLE
Clicking on a demo image makes the upload button not work

### ISSUE THREAD

**Issue by justingolden21** [NotWoods/maskable#43]
Clicking on a demo image at the top takes you to something like: https://maskable.app/?demo=demo/spec.svg

Which makes "Open icon file" not work:

![image](https://user-images.githubusercontent.com/30274440/107156055-e407df80-6930-11eb-8d39-45bffd844c5e.png)

Also, from this screen, there's no button/navigator to go to the editor (https://maskable.app/editor)

**Comment by NotWoods** [comment]
There is an editor link at the bottom, but it definitely needs to be updated to made more clear.

**Comment by NotWoods** [comment]
What device are you using? I'm able to open icon files from Firefox and Chromium on Windows.

**Comment by justingolden21** [comment]
I'm using the latest stable version of Google Chrome on Chrome OS.

EDIT: Now it works... I also just realized that I can go to the editor tab up top... I never realized that last time. I'd consider adding a CTA button that takes them to the editor at the bottom of the page as well, for UX and good visual hierarchy.

Thanks for the quick reply btw
