### ISSUE TITLE
Preview masks don't affect the file downloaded

### ISSUE THREAD

**Issue by justingolden21** [NotWoods/maskable#44]

**Comment by justingolden21** [comment]
The preview masks:
![image](https://user-images.githubusercontent.com/30274440/107156264-3695cb80-6932-11eb-91a4-5e92641c3e69.png)

don't affect the generated files. Selecting circle or rounded rectangle only affects the view in browser, and the file generated is always a rectangle. If this is intended, it should be communicated better. Either way, it would be a nice feature to have.

**Comment by justingolden21** [comment]
(Apologies for the edits, github is dumb and hitting enter once while typing the title accidently submitted the whole thing, then editing the title didn't go through since you can apparently type in both inputs at once, but it only updates the body)

**Comment by justingolden21** [comment]
> This layer cannot be deleted or made translucent as maskable icons should always be opaque.

Ah, I see this now. I expected the exported icon to be transparent in the areas not shown in the mask (outsides of the circle/rect/tear)

**Comment by NotWoods** [comment]
Maskable icons are designed to be clipped by the operating system. I'll try to update the description at the bottom to make it more clear.
