### ISSUE TITLE
Feature: Add option to view a Samsung like mask

### ISSUE THREAD

**Issue by nstringham** [NotWoods/maskable#68]
Samsung makes up a large portion of Android devices and has a unique icon shape. It would be useful to be able to preview this icon shape in the viewer

**Comment by NotWoods** [comment]
For now there's a secret mode to turn this on: https://maskable.app/?secret. I haven't turned these on by default yet because I can't animate the additional shapes. I might investigate new UI to turn masks on/off.

**Comment by nstringham** [comment]
Thanks! Is there a way to make the website always open in secret mode? or do I have to type it every time?

**Comment by NotWoods** [comment]
At the moment you need to type it every time. You can bookmark the new URL so it autocompletes.
