### ISSUE TITLE
maskable.app down

### ISSUE THREAD

**Issue by easrng** [NotWoods/maskable#78]

**Comment by NotWoods** [comment]
I'm still able to access https://maskable.app/

**Comment by easrng** [comment]
looks like it was a DNS problem on my end, weird.

**Comment by easrng** [comment]
looks like it's [blocked by quad9](https://www.quad9.net/result/?url=maskable.app) :/
guess i'll stop using them

**Comment by NotWoods** [comment]
Thanks for checking and sending over the article! I'll see if I can ping quad9 later.
